version: '3'

services: 
  nodejs:
    build: .
    command: node index.js
    volumes: 
      - ./app_backend:/home/node/app
    ports: 
      - "3000:3000"
    depends_on: 
      - postgres
    environment: 
      POSTGRES_HOST: postgres
      POSTGRES_DB: apidb
      POSTGRES_USER: appuser
      POSTGRES_PORT: 5432
    networks: 
      - app-network

  postgres:
    image: postgres:alpine
    environment: 
      POSTGRES_USER: appuser
      POSTGRES_DB: apidb
    volumes: 
      - ./app_backend/config/sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports: 
      - "5432:5432"
    networks: 
      - app-network

  angular-service:
    build: ./app-front-end
    volumes: 
      - ./app-front-end:/home/node/app
    ports:
      - "4200:4200"
    command: ng serve
    depends_on: 
      - nodejs

networks: 
  app-network:
      driver: bridge